### ISSUE TITLE
Problem running on a stack or folder of multiple images (tuple index out of range)

### ISSUE THREAD

**Issue by babo989** [MouseLand/cellpose-napari#10]
I get a 'tuple index out of range' error when trying to load multiple images, the segmentation works great on a single image.
Any ideas?

**Comment by psobolewskiPhD** [comment]
For a folder of images, check out:
https://github.com/guiwitz/napari-serialcellpose

**Comment by carsen-stringer** [comment]
thanks @tlambert03 and @psobolewskiPhD
