### ISSUE TITLE
segmentation ends with `tuple index out of range`

### ISSUE THREAD

**Issue by Czaki** [MouseLand/cellpose-napari#12]
When run segmentation on 3d stack it ends with `tuple index out of range` As it is some error in the segmentation process it should be raised in a way which allow understanding what happens.

**Comment by chili-chiu** [comment]
Ran into the same error message when segmenting 3D stack. Check "process stack as 3D" avoids the error. By default it is unchecked.

**Comment by tlambert03** [comment]
duplicate of #10
