### ISSUE TITLE
Problem with cellpose-napari (logger import error)

### ISSUE THREAD

**Issue by camcaminin9** [MouseLand/cellpose-napari#21]
Hello! I am trying to get to work cellpose-napari. I am using a mac with M1 Chip, with anaconda3. I created a new environment following the instructions given on the documentation (https://napari.org/). 
conda create -y -n napari-env python=3.8
conda activate napari-env
pip install "napari[all]"
Napari opened correctly, then I installed cellpose-napari internally.

Once I load an image and try to run a segmentation, I get this error message: 

<img width="1329" alt="Screenshot 2022-01-31 at 15 52 12" src="https://user-images.githubusercontent.com/98757008/151815467-87f75ade-52bc-4b46-a46b-5f2fafd01146.png">

I tried with both python 3.8 and 3.9, but the same happens. Do you maybe have an idea of what is causing this problem and how to solve it?
Thank you very much
Camilla

**Comment by tlambert03** [comment]
Hi @camcaminin9, I noticed this as well.  see https://github.com/MouseLand/cellpose-napari/issues/20

try downgrading cellpose for now: pip install cellpose==0.6.5

**Comment by tlambert03** [comment]
the napari widget should _also_ work if you downgrade cellpose to < 0.7.  The point is, this widget was designed for <= 0.6.5, the upstream library made some changes in the meantime, and this plugin hasn't yet been updated.  so, you can use this widget, but only with older versions of the core cellpose library

**Comment by camcaminin9** [comment]
Thank you very much. Indeed it is solved in this way

**Comment by tlambert03** [comment]
fixed by #29, in newest release
