### ISSUE TITLE
ROI manager compatible output for ImageJ/Fiji

### ISSUE THREAD

**Issue by Minarazagh** [MouseLand/cellpose-napari#23]
After running segmentation in napari, I need to analyze my images in Fiji environment.  In the cell pose guideline book you wrote command lines that we can save outline.txt and I have done that for google Collab environment and it did work pretty well. However, I am wondering how export outline and mask from napari to the Fiji ROI manager.

Any help would be appreciate it!
Thanks!

**Comment by psobolewskiPhD** [comment]
Try: https://labelstorois.github.io
using the labels/masks output from cellpose.
If you scroll down there is an example video with cellpose.

**Comment by carsen-stringer** [comment]
thanks @psobolewskiPhD
