### ISSUE TITLE
Failed to build numba opencv-python-headless

### ISSUE THREAD

**Issue by emoebel** [MouseLand/cellpose-napari#25]
So I am trying to install cellpose-napari through the Napari GUI (Plugins->Install/Uninstall), but I get following error:
```
Failed to build numba opencv-python-headless
ERROR: Could not build wheels for opencv-python-headless which use PEP 517 and cannot be installed directly
```
Attached you can find the complete error print. I am using macOS 10.12.6, Python 3.7.11 and Conda 4.12.0

Any idea ?
[cellpose-napari_error.txt](https://github.com/MouseLand/cellpose-napari/files/8668882/cellpose-napari_error.txt)

**Comment by tlambert03** [comment]
sorry i don't, but this is an issue with `opencv-python-headless` rather than this plugin.  You might ask them for help: https://github.com/opencv/opencv-python
