### ISSUE TITLE
CellPose-napari and TensorFlow

### ISSUE THREAD

**Issue by samueljrosen** [MouseLand/cellpose-napari#26]
I am currently trying to use CellPose-napari with TensorFlow but have run into multiple install issues. When I install CellPose-napari and TensorFlow into separate environments, they run fine so I believe this to be an issue with the different versions of numpy, scipy and the likes causing conflicts. If someone has a pre-existing environment where they have gotten the two to run together, that would be perfect or any guidance on having both TensorFlow and CellPose-napari work together would be great. Thank you so much!

**Comment by carsen-stringer** [comment]
ideally tensorflow and pytorch work well together now, but can reopen the issue if not (they work fine together for me now on linux)
