### ISSUE TITLE
CellPose Napari plugin does not consider scale of original layer

### ISSUE THREAD

**Issue by sebi06** [MouseLand/cellpose-napari#37]
Hi all,

I just tested the CellPose plugin in Napari and it seems the its output does not have the same scale a the original layer (to be segmented): For a detailed description check:

https://forum.image.sc/t/cellpose-napatri-plugin-does-not-consider-scale-of-original-layer/70919?u=sebi06

**Comment by carsen-stringer** [comment]
thanks @psobolewskiPhD for fixing this, I think it should be working now?
