### ISSUE TITLE
Cell segmentation XYZ coordinates export

### ISSUE THREAD

**Issue by alfonsecard** [MouseLand/cellpose-napari#42]
Hi, thanks a lot for developing this software. I've been struggling with cell segmentation in 3D for a long time and your software is working so well after training the model with a few images.

I am able to obtain very accurate cell masks in 3D, but now I'm having problems converting this data into an XYZ coordinates text file (that I need for a subsequent smFISH-dot count analysis).

Do you have any recommendations on how I can obtain this? 

Bests.

**Comment by carsen-stringer** [comment]
for each mask in a 3D `masks` array, its XYZ coordinates are:
```
for m in range(1, masks.max()):
    z, y, x = np.nonzero(masks==m)
```
