### ISSUE TITLE
4D stack segmentation appears smashed at the top of the image.

### ISSUE THREAD

**Issue by TroySeman** [MouseLand/cellpose-napari#47]
I loaded the images from file folder.  I have 50 image tiff stacks in the Z direction, then 224 of these stacks in the time dimension.  Both sliders in Napari show 0 through 223.  I eventually got everything to run without getting pickling errors (I'm not sure how I got these to go away)  I ran everything through with my custom model but the added segmentation layers all appear smashed up at the top of the image above the original frame boundary instead of fitted to and overlaying the original image frames.  (See attached)  I don't how or why the outputs came like this.  Please help.  See the attached image.  the colored blotches above the black and white image are the detection.

Detection runs but it puts the segmented layers in a smooshed series of images above the original image frames.  It also changes the first slider bar to 0 - 223  just like the one below it.  What happens then is the top bar will index through the Z dimension from 0 to 49 then go black while also indexing through the smashed segmentations at the top all the way through to the 233rd setting.  The bottom  bar still works the same, indexing through the time dimension on the current Z slice. But the smooshed segmentations stay where they were last set with the top bar.

<img width="1280" alt="Wierd detection layers" src="https://github.com/MouseLand/cellpose-napari/assets/19415564/1489cc76-b9db-469f-a2ca-9aea20bed1f6">

Thank you

**Comment by carsen-stringer** [comment]
this seems like a napari loading error, might be good to post on their repo -- if you have a tif of size 50x223xLyxLx it should show up with 2 sliders, one of size 50 and one of size 223
