### ISSUE TITLE
Error after installing

### ISSUE THREAD

**Issue by mafsousa** [MouseLand/cellpose-napari#5]
I'm trying to install it on windows and followed all the steps but by the end running

napari -w cellpose-napari 

is giving the error:

"Plugin 'cellpose-napari' does not provide any dock widgets"

I also tried installing from the napari GUI, and it appears installed with the possibility to update to v 0.1.3. If I click update I got the error:

 Cannot find the MXNet library.

Although I have installed mxnet, the version 1.4.0, suggested in cellpose installation guide,  was not available.

**Comment by tlambert03** [comment]
if you run `napari --plugin-info -v` does it provide any additional info about the error?

**Comment by mafsousa** [comment]
I solved the problem after creating a few conda envs with different configurations. Maybe some installation conflicts!
